services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.production

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production